{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "90c81c48",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "INFO:     Started server process [4902]\n",
      "INFO:     Waiting for application startup.\n",
      "INFO:     Application startup complete.\n",
      "INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)\n",
      "Database Error\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/allenem/projects/python/niagads-pylib/components/niagads/database/session/core.py\", line 82, in __call__\n",
      "    yield session\n",
      "  File \"/home/allenem/projects/python/niagads-pylib/.venv/lib/python3.12/site-packages/fastapi/routing.py\", line 301, in app\n",
      "    raw_response = await run_endpoint_function(\n",
      "                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/allenem/projects/python/niagads-pylib/.venv/lib/python3.12/site-packages/fastapi/routing.py\", line 212, in run_endpoint_function\n",
      "    return await dependant.call(**values)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/allenem/projects/python/niagads-pylib/bases/niagads/open_access_filer_api/routes/root.py\", line 34, in get_route_description\n",
      "    trackCount = await MetadataQueryService(\n",
      "                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/allenem/projects/python/niagads-pylib/components/niagads/open_access_api_common/services/metadata/query.py\", line 67, in get_track_count\n",
      "    result = (await self.__session.execute(statement)).scalars().first()\n",
      "              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/allenem/projects/python/niagads-pylib/.venv/lib/python3.12/site-packages/sqlalchemy/ext/asyncio/session.py\", line 463, in execute\n",
      "    result = await greenlet_spawn(\n",
      "             ^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/allenem/projects/python/niagads-pylib/.venv/lib/python3.12/site-packages/sqlalchemy/util/_concurrency_py3k.py\", line 201, in greenlet_spawn\n",
      "    result = context.throw(*sys.exc_info())\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/allenem/projects/python/niagads-pylib/.venv/lib/python3.12/site-packages/sqlalchemy/orm/session.py\", line 2365, in execute\n",
      "    return self._execute_internal(\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/allenem/projects/python/niagads-pylib/.venv/lib/python3.12/site-packages/sqlalchemy/orm/session.py\", line 2241, in _execute_internal\n",
      "    conn = self._connection_for_bind(bind)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/allenem/projects/python/niagads-pylib/.venv/lib/python3.12/site-packages/sqlalchemy/orm/session.py\", line 2110, in _connection_for_bind\n",
      "    return trans._connection_for_bind(engine, execution_options)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"<string>\", line 2, in _connection_for_bind\n",
      "  File \"/home/allenem/projects/python/niagads-pylib/.venv/lib/python3.12/site-packages/sqlalchemy/orm/state_changes.py\", line 139, in _go\n",
      "    ret_value = fn(self, *arg, **kw)\n",
      "                ^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/allenem/projects/python/niagads-pylib/.venv/lib/python3.12/site-packages/sqlalchemy/orm/session.py\", line 1189, in _connection_for_bind\n",
      "    conn = bind.connect()\n",
      "           ^^^^^^^^^^^^^^\n",
      "  File \"/home/allenem/projects/python/niagads-pylib/.venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py\", line 3274, in connect\n",
      "    return self._connection_cls(self)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/allenem/projects/python/niagads-pylib/.venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py\", line 146, in __init__\n",
      "    self._dbapi_connection = engine.raw_connection()\n",
      "                             ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/allenem/projects/python/niagads-pylib/.venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py\", line 3298, in raw_connection\n",
      "    return self.pool.connect()\n",
      "           ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/allenem/projects/python/niagads-pylib/.venv/lib/python3.12/site-packages/sqlalchemy/pool/base.py\", line 449, in connect\n",
      "    return _ConnectionFairy._checkout(self)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/allenem/projects/python/niagads-pylib/.venv/lib/python3.12/site-packages/sqlalchemy/pool/base.py\", line 1264, in _checkout\n",
      "    fairy = _ConnectionRecord.checkout(pool)\n",
      "            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/allenem/projects/python/niagads-pylib/.venv/lib/python3.12/site-packages/sqlalchemy/pool/base.py\", line 713, in checkout\n",
      "    rec = pool._do_get()\n",
      "          ^^^^^^^^^^^^^^\n",
      "  File \"/home/allenem/projects/python/niagads-pylib/.venv/lib/python3.12/site-packages/sqlalchemy/pool/impl.py\", line 179, in _do_get\n",
      "    with util.safe_reraise():\n",
      "  File \"/home/allenem/projects/python/niagads-pylib/.venv/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py\", line 146, in __exit__\n",
      "    raise exc_value.with_traceback(exc_tb)\n",
      "  File \"/home/allenem/projects/python/niagads-pylib/.venv/lib/python3.12/site-packages/sqlalchemy/pool/impl.py\", line 177, in _do_get\n",
      "    return self._create_connection()\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/allenem/projects/python/niagads-pylib/.venv/lib/python3.12/site-packages/sqlalchemy/pool/base.py\", line 390, in _create_connection\n",
      "    return _ConnectionRecord(self)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/allenem/projects/python/niagads-pylib/.venv/lib/python3.12/site-packages/sqlalchemy/pool/base.py\", line 675, in __init__\n",
      "    self.__connect()\n",
      "  File \"/home/allenem/projects/python/niagads-pylib/.venv/lib/python3.12/site-packages/sqlalchemy/pool/base.py\", line 901, in __connect\n",
      "    with util.safe_reraise():\n",
      "  File \"/home/allenem/projects/python/niagads-pylib/.venv/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py\", line 146, in __exit__\n",
      "    raise exc_value.with_traceback(exc_tb)\n",
      "  File \"/home/allenem/projects/python/niagads-pylib/.venv/lib/python3.12/site-packages/sqlalchemy/pool/base.py\", line 897, in __connect\n",
      "    self.dbapi_connection = connection = pool._invoke_creator(self)\n",
      "                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/allenem/projects/python/niagads-pylib/.venv/lib/python3.12/site-packages/sqlalchemy/engine/create.py\", line 646, in connect\n",
      "    return dialect.connect(*cargs, **cparams)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/allenem/projects/python/niagads-pylib/.venv/lib/python3.12/site-packages/sqlalchemy/engine/default.py\", line 625, in connect\n",
      "    return self.loaded_dbapi.connect(*cargs, **cparams)  # type: ignore[no-any-return]  # NOQA: E501\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/allenem/projects/python/niagads-pylib/.venv/lib/python3.12/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py\", line 961, in connect\n",
      "    await_only(creator_fn(*arg, **kw)),\n",
      "    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/allenem/projects/python/niagads-pylib/.venv/lib/python3.12/site-packages/sqlalchemy/util/_concurrency_py3k.py\", line 132, in await_only\n",
      "    return current.parent.switch(awaitable)  # type: ignore[no-any-return,attr-defined] # noqa: E501\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/allenem/projects/python/niagads-pylib/.venv/lib/python3.12/site-packages/sqlalchemy/util/_concurrency_py3k.py\", line 196, in greenlet_spawn\n",
      "    value = await result\n",
      "            ^^^^^^^^^^^^\n",
      "  File \"/home/allenem/projects/python/niagads-pylib/.venv/lib/python3.12/site-packages/asyncpg/connection.py\", line 2421, in connect\n",
      "    return await connect_utils._connect(\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/allenem/projects/python/niagads-pylib/.venv/lib/python3.12/site-packages/asyncpg/connect_utils.py\", line 1075, in _connect\n",
      "    raise last_error or exceptions.TargetServerAttributeNotMatched(\n",
      "  File \"/home/allenem/projects/python/niagads-pylib/.venv/lib/python3.12/site-packages/asyncpg/connect_utils.py\", line 1049, in _connect\n",
      "    conn = await _connect_addr(\n",
      "           ^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/allenem/projects/python/niagads-pylib/.venv/lib/python3.12/site-packages/asyncpg/connect_utils.py\", line 886, in _connect_addr\n",
      "    return await __connect_addr(params, True, *args)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/allenem/projects/python/niagads-pylib/.venv/lib/python3.12/site-packages/asyncpg/connect_utils.py\", line 931, in __connect_addr\n",
      "    tr, pr = await connector\n",
      "             ^^^^^^^^^^^^^^^\n",
      "  File \"/home/allenem/projects/python/niagads-pylib/.venv/lib/python3.12/site-packages/asyncpg/connect_utils.py\", line 802, in _create_ssl_connection\n",
      "    tr, pr = await loop.create_connection(\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/usr/lib/python3.12/asyncio/base_events.py\", line 1122, in create_connection\n",
      "    raise exceptions[0]\n",
      "  File \"/usr/lib/python3.12/asyncio/base_events.py\", line 1104, in create_connection\n",
      "    sock = await self._connect_sock(\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/usr/lib/python3.12/asyncio/base_events.py\", line 1007, in _connect_sock\n",
      "    await self.sock_connect(sock, address)\n",
      "  File \"/usr/lib/python3.12/asyncio/selector_events.py\", line 651, in sock_connect\n",
      "    return await fut\n",
      "           ^^^^^^^^^\n",
      "  File \"/usr/lib/python3.12/asyncio/selector_events.py\", line 691, in _sock_connect_cb\n",
      "    raise OSError(err, f'Connect call failed {address}')\n",
      "ConnectionRefusedError: [Errno 111] Connect call failed ('127.0.0.1', 5445)\n",
      "Stack (most recent call last):\n",
      "  File \"<frozen runpy>\", line 198, in _run_module_as_main\n",
      "  File \"<frozen runpy>\", line 88, in _run_code\n",
      "  File \"/home/allenem/projects/python/niagads-pylib/.venv/lib/python3.12/site-packages/ipykernel_launcher.py\", line 18, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"/home/allenem/projects/python/niagads-pylib/.venv/lib/python3.12/site-packages/traitlets/config/application.py\", line 1075, in launch_instance\n",
      "    app.start()\n",
      "  File \"/home/allenem/projects/python/niagads-pylib/.venv/lib/python3.12/site-packages/ipykernel/kernelapp.py\", line 739, in start\n",
      "    self.io_loop.start()\n",
      "  File \"/home/allenem/projects/python/niagads-pylib/.venv/lib/python3.12/site-packages/tornado/platform/asyncio.py\", line 205, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"/usr/lib/python3.12/asyncio/base_events.py\", line 641, in run_forever\n",
      "    self._run_once()\n",
      "  File \"/usr/lib/python3.12/asyncio/base_events.py\", line 1987, in _run_once\n",
      "    handle._run()\n",
      "  File \"/usr/lib/python3.12/asyncio/events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"/home/allenem/projects/python/niagads-pylib/.venv/lib/python3.12/site-packages/uvicorn/protocols/http/h11_impl.py\", line 403, in run_asgi\n",
      "    result = await app(  # type: ignore[func-returns-value]\n",
      "  File \"/home/allenem/projects/python/niagads-pylib/.venv/lib/python3.12/site-packages/uvicorn/middleware/proxy_headers.py\", line 60, in __call__\n",
      "    return await self.app(scope, receive, send)\n",
      "  File \"/home/allenem/projects/python/niagads-pylib/.venv/lib/python3.12/site-packages/fastapi/applications.py\", line 1054, in __call__\n",
      "    await super().__call__(scope, receive, send)\n",
      "  File \"/home/allenem/projects/python/niagads-pylib/.venv/lib/python3.12/site-packages/starlette/applications.py\", line 112, in __call__\n",
      "    await self.middleware_stack(scope, receive, send)\n",
      "  File \"/home/allenem/projects/python/niagads-pylib/.venv/lib/python3.12/site-packages/starlette/middleware/errors.py\", line 165, in __call__\n",
      "    await self.app(scope, receive, _send)\n",
      "  File \"/home/allenem/projects/python/niagads-pylib/.venv/lib/python3.12/site-packages/starlette/middleware/cors.py\", line 85, in __call__\n",
      "    await self.app(scope, receive, send)\n",
      "  File \"/home/allenem/projects/python/niagads-pylib/.venv/lib/python3.12/site-packages/asgi_correlation_id/middleware.py\", line 90, in __call__\n",
      "    await self.app(scope, receive, handle_outgoing_request)\n",
      "  File \"/home/allenem/projects/python/niagads-pylib/.venv/lib/python3.12/site-packages/starlette/middleware/exceptions.py\", line 62, in __call__\n",
      "    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)\n",
      "  File \"/home/allenem/projects/python/niagads-pylib/.venv/lib/python3.12/site-packages/starlette/_exception_handler.py\", line 42, in wrapped_app\n",
      "    await app(scope, receive, sender)\n",
      "  File \"/home/allenem/projects/python/niagads-pylib/.venv/lib/python3.12/site-packages/starlette/routing.py\", line 714, in __call__\n",
      "    await self.middleware_stack(scope, receive, send)\n",
      "  File \"/home/allenem/projects/python/niagads-pylib/.venv/lib/python3.12/site-packages/starlette/routing.py\", line 734, in app\n",
      "    await route.handle(scope, receive, send)\n",
      "  File \"/home/allenem/projects/python/niagads-pylib/.venv/lib/python3.12/site-packages/starlette/routing.py\", line 288, in handle\n",
      "    await self.app(scope, receive, send)\n",
      "  File \"/home/allenem/projects/python/niagads-pylib/.venv/lib/python3.12/site-packages/starlette/routing.py\", line 76, in app\n",
      "    await wrap_app_handling_exceptions(app, request)(scope, receive, send)\n",
      "  File \"/home/allenem/projects/python/niagads-pylib/.venv/lib/python3.12/site-packages/starlette/_exception_handler.py\", line 42, in wrapped_app\n",
      "    await app(scope, receive, sender)\n",
      "  File \"/home/allenem/projects/python/niagads-pylib/.venv/lib/python3.12/site-packages/starlette/routing.py\", line 73, in app\n",
      "    response = await f(request)\n",
      "  File \"/home/allenem/projects/python/niagads-pylib/.venv/lib/python3.12/site-packages/fastapi/routing.py\", line 290, in app\n",
      "    async with AsyncExitStack() as async_exit_stack:\n",
      "  File \"/usr/lib/python3.12/contextlib.py\", line 737, in __aexit__\n",
      "    cb_suppress = await cb(*exc_details)\n",
      "  File \"/usr/lib/python3.12/contextlib.py\", line 231, in __aexit__\n",
      "    await self.gen.athrow(value)\n",
      "  File \"/home/allenem/projects/python/niagads-pylib/components/niagads/database/session/core.py\", line 88, in __call__\n",
      "    self.logger.error(\"Database Error\", exc_info=err, stack_info=True)\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "INFO:     127.0.0.1:51262 - \"GET / HTTP/1.1\" 422 Unprocessable Entity\n",
      "INFO:     127.0.0.1:51266 - \"GET /favicon.ico HTTP/1.1\" 404 Not Found\n"
     ]
    }
   ],
   "source": [
    "from run_service import start_local_service\n",
    "start_local_service('filer')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "ca958817",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": ".venv",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
